git rm    KyoroCommon/src/info/kyorohiro/helloworld/io/BigLineDataBuilder.java
git rm    KyoroCommon/src/info/kyorohiro/helloworld/io/charset/ISO2022.java
git rm    KyoroCommon/src/info/kyorohiro/helloworld/io/charset/ISO2022CN.java
git rm    KyoroCommon/src/info/kyorohiro/helloworld/io/charset/ISO2022JP.java
git rm    KyoroCommon/src/info/kyorohiro/helloworld/io/charset/ISO2022KR.java
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/TestISO2022CN.java
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/TestISO2022JP.java
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/TestISO2022KR.java
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/iso_2022_cn_crlf_001.txt
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/iso_2022_jp_crlf_001.txt
git rm    KyoroCommon/test/info/kyorohiro/helloworld/io/charset/iso_2022_kr_crlf_001.txt
